"use client";import {useActionState,useState} from "react";import {createVehicleAction,type ActionState} from "../actions";const initial:ActionState={};
type Props={fleetCompanies:string[];tireDealers:string[];vehicleTypes:string[];fuelTypes:string[];transmissions:string[]};
export function VehicleForm({fleetCompanies,tireDealers,vehicleTypes,fuelTypes,transmissions}:Props){const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());const[state,action,pending]=useActionState(createVehicleAction,initial);const[ownership,setOwnership]=useState("FLEET");return <form action={action} className="card modal-card"><div className="section-head"><div className="section-title">Yeni Araç</div></div><div className="section-body">{state.error?<div className="error-box" style={{marginBottom:14}}>{state.error}</div>:null}<div className="form-grid">
<div className="field"><label>Plaka *</label><input name="plate" className="input" placeholder="34 MAS 831" required/></div><div className="field"><label>Mülkiyet Tipi *</label><select name="ownership_type" className="select" value={ownership} onChange={e=>setOwnership(e.target.value)}><option value="FLEET">Kiralık / Filo</option><option value="OWNED">Özmal</option></select></div>
<div className="field"><label>Marka *</label><input name="brand" className="input" required/></div><div className="field"><label>Model *</label><input name="model" className="input" required/></div><div className="field"><label>Model Yılı *</label><input name="model_year" type="number" className="input" defaultValue={new Date().getFullYear()} required/></div>
<div className="field"><label>Araç Tipi *</label>{vehicleTypes.length?<select name="vehicle_type" className="select" required defaultValue=""><option value="" disabled>Seçin</option>{vehicleTypes.map(x=><option key={x}>{x}</option>)}</select>:<input name="vehicle_type" className="input" required/>}</div>
<div className="field"><label>Yakıt Tipi</label>{fuelTypes.length?<select name="fuel_type" className="select" defaultValue=""><option value="">Seçin</option>{fuelTypes.map(x=><option key={x}>{x}</option>)}</select>:<input name="fuel_type" className="input"/>}</div><div className="field"><label>Şanzıman</label>{transmissions.length?<select name="transmission" className="select" defaultValue=""><option value="">Seçin</option>{transmissions.map(x=><option key={x}>{x}</option>)}</select>:<input name="transmission" className="input"/>}</div><div className="field"><label>Renk</label><input name="color" className="input"/></div>
<div className="field"><label>Şasi Numarası</label><input name="vin" className="input"/></div><div className="field"><label>Motor Numarası</label><input name="engine_number" className="input"/></div><div className="field"><label>Ruhsat Seri No</label><input name="registration_serial_no" className="input"/></div><div className="field"><label>Ruhsat Belge No</label><input name="registration_document_no" className="input"/></div><div className="field"><label>Tescil Tarihi</label><input name="registration_date" type="date" max={today} className="input"/></div>
<div className="field"><label>Güncel KM *</label><input name="current_odometer" type="number" min="1" className="input" defaultValue="0" required/></div><div className="field"><label>Sorumlu Kişi</label><input name="responsible_person" className="input"/></div><div className="field"><label>Durum *</label><select name="status" className="select" defaultValue="ACTIVE"><option value="ACTIVE">Boşta</option><option value="MAINTENANCE">Bakımda</option><option value="INACTIVE">Kullanım Dışı</option></select></div>
<div className="field"><label>Lastik Depo Bayisi *</label>{tireDealers.length?<select name="tire_storage_dealer" className="select" required defaultValue=""><option value="" disabled>Seçin</option>{tireDealers.map(x=><option key={x}>{x}</option>)}</select>:<input name="tire_storage_dealer" className="input" required/>}<small>Sistemde tanımlı lastik depo bayilerinden seçim yapın.</small></div>
{ownership==="FLEET"?<><div className="field"><label>Filo Şirketi *</label>{fleetCompanies.length?<select name="fleet_company" className="select" required defaultValue=""><option value="" disabled>Seçin</option>{fleetCompanies.map(x=><option key={x}>{x}</option>)}</select>:<input name="fleet_company" className="input" required/>}</div><div className="field"><label>Sözleşme Başlangıç Tarihi</label><input name="contract_start_date" type="date" max={today} className="input"/></div><div className="field"><label>Sözleşme Bitiş Tarihi</label><input name="contract_end_date" type="date" className="input"/></div><div className="field"><label>Sözleşme KM Limiti</label><input name="contract_km_limit" type="number" min="1" className="input"/></div><div className="field"><label>Sözleşme Referans / Araç No</label><input name="contract_reference" className="input"/></div><div className="field"><label>İade Planlanan Tarih</label><input name="planned_return_date" type="date" className="input"/></div><div className="field" style={{gridColumn:"1 / -1"}}><label>Açıklama</label><textarea name="fleet_description" className="textarea" rows={3}/></div></>:null}</div><div className="form-actions"><a href="/araclar" className="btn btn-secondary">Vazgeç</a><button className="btn btn-primary" disabled={pending}>{pending?"Kaydediliyor...":"Kaydet"}</button></div></div></form>}
