import {PersonnelSnapshot} from "@/components/personnel-snapshot";
import Link from "next/link";
import {notFound} from "next/navigation";
import {requireUser} from "@/lib/auth";
import {getDatabase} from "@/lib/local/database";
import {formatDateTime} from "@/lib/format";
import {SubmitButton} from "@/components/submit-button";

export const dynamic="force-dynamic";

export default async function PersonnelAssetDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{saved?:string;error?:string;upload?:string;upload_message?:string}>}){
  await requireUser();
  const {id}=await params,sp=await searchParams,db=getDatabase();
  const p=db.prepare("SELECT * FROM personnel WHERE id=?").get(id) as any;if(!p)notFound();
  const rows=db.prepare(`SELECT pa.*,e.equipment_type,e.brand,e.model,e.serial_number,e.imei,e.imei2,e.asset_tag,e.status equipment_status FROM personnel_assignments pa JOIN equipment e ON e.id=pa.equipment_id WHERE pa.personnel_id=? ORDER BY (pa.return_date IS NULL) DESC,pa.assignment_date DESC,pa.created_at DESC,pa.id DESC`).all(id) as any[];
  const docs=db.prepare(`SELECT a.id attachment_id,a.entity_id,av.id version_id,av.original_filename,av.version_number,av.uploaded_at FROM attachments a JOIN attachment_versions av ON av.attachment_id=a.id WHERE a.entity_type='personnel_assignment' AND a.entity_id IN (SELECT id FROM personnel_assignments WHERE personnel_id=?) AND a.is_active=1 AND av.version_number=(SELECT MAX(v2.version_number) FROM attachment_versions v2 WHERE v2.attachment_id=a.id)`).all(id) as any[];
  const docMap=new Map(docs.map((d:any)=>[d.entity_id,d]));
  const active=rows.filter(x=>x.status==="ACTIVE"&&!x.return_date),history=rows.filter(x=>x.status!=="ACTIVE"||x.return_date);
  const parts=new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date());const n=Object.fromEntries(parts.map(x=>[x.type,x.value]));const nowLocal=`${n.year}-${n.month}-${n.day}T${n.hour}:${n.minute}`;
  const documentCell=(x:any)=>{const d=docMap.get(x.id) as any;return d?<div className="row-actions"><a className="btn btn-secondary" target="_blank" href={`/api/attachments/version/${d.version_id}`}>Görüntüle</a><a className="btn btn-secondary" href={`/api/attachments/version/${d.version_id}?download=1`}>İndir</a></div>:<span className="page-sub">Belge yok</span>};
  return <>
    <div className="page-head"><div><Link className="page-sub" href="/personel-zimmetleri">← Personel Zimmetleri</Link><h1 className="page-title" style={{marginTop:6}}>{p.first_name} {p.last_name}</h1><div className="page-sub">{[p.company,p.branch,p.department].filter(Boolean).join(" • ")||"Personel kartı"}</div></div><div className="page-actions"><Link className="btn btn-secondary" href={`/personel-yonetimi/${id}`}>Personel Bilgileri</Link><span className={`pill ${p.status==="ACTIVE"?"green":"gray"}`}>{p.status==="ACTIVE"?"Aktif":p.status==="DELETED"?"Silindi • Geçmiş korundu":"Geçmiş kayıt"}</span></div></div>
    {sp.saved?<div className="success-box">Değişiklik kaydedildi.</div>:null}{sp.error?<div className="error-box">{decodeURIComponent(sp.error)}</div>:null}{sp.upload==="error"?<div className="error-box">{sp.upload_message||"Dosya yüklenemedi."}</div>:null}
    <div className="grid-kpi section"><div className="card kpi"><div className="kpi-label">Aktif Zimmet</div><div className="kpi-value">{active.length}</div></div><div className="card kpi"><div className="kpi-label">Geçmiş Zimmet</div><div className="kpi-value">{history.length}</div></div></div>
    <section className="card section table-wrap"><div className="section-head"><div><div className="section-title">Aktif Zimmetler</div><div className="page-sub">Şu anda personel üzerinde bulunan ekipmanlar.</div></div></div><table className="table"><thead><tr><th>Ekipman</th><th>Demirbaş / Seri No</th><th>Zimmet Tarihi</th><th>Durum</th><th>Belge</th><th>İşlem</th></tr></thead><tbody>{active.map(x=><tr key={x.id}><td><Link className="link-primary" href={`/personel-zimmetleri/demirbas/${x.equipment_id}`}>{[x.equipment_type,x.brand,x.model].filter(Boolean).join(" ")}</Link></td><td>{x.asset_tag||"—"}<div className="page-sub">{x.serial_number?`SN: ${x.serial_number}`:x.imei?`IMEI: ${x.imei}`:""}</div></td><td>{formatDateTime(x.assignment_date)}<PersonnelSnapshot value={x.personnel_snapshot}/></td><td><span className="pill blue">Aktif Zimmet</span></td><td>{documentCell(x)}</td><td><form action="/api/personnel-assets" method="post" className="inline-return-form"><input type="hidden" name="operation" value="return"/><input type="hidden" name="assignment_id" value={x.id}/><input type="hidden" name="return_to" value={`/personel-zimmetleri/personel/${id}`}/><input className="input" type="datetime-local" name="return_date" min={String(x.assignment_date).slice(0,16)} max={nowLocal} required/><select className="select" name="status" defaultValue="RETURNED"><option value="RETURNED">İade / Havuzda</option><option value="DAMAGED">Hasarlı</option></select><input className="input" name="return_note" placeholder="İade notu"/><SubmitButton>Zimmetten Düşür / İade Al</SubmitButton></form></td></tr>)}</tbody></table>{!active.length?<div className="empty"><strong>Aktif zimmet yok.</strong>Bu personelde şu anda ekipman bulunmuyor.</div>:null}</section>
    <section className="card section table-wrap"><div className="section-head"><div><div className="section-title">Geçmiş Zimmetler</div><div className="page-sub">İade, hasar veya kayıp ile tamamlanan tüm zimmet kayıtları korunur.</div></div></div><table className="table"><thead><tr><th>Ekipman</th><th>Demirbaş / Seri No</th><th>Zimmet</th><th>İade</th><th>Durum</th><th>Açıklama</th><th>Belge</th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td><Link className="link-primary" href={`/personel-zimmetleri/demirbas/${x.equipment_id}`}>{[x.equipment_type,x.brand,x.model].filter(Boolean).join(" ")}</Link></td><td>{x.asset_tag||x.serial_number||x.imei||"—"}</td><td>{formatDateTime(x.assignment_date)}<PersonnelSnapshot value={x.personnel_snapshot}/></td><td>{formatDateTime(x.return_date)}</td><td><span className={`pill ${x.status==="RETURNED"?"green":x.status==="DAMAGED"?"orange":"red"}`}>{x.status==="RETURNED"?"İade Edildi":x.status==="DAMAGED"?"Hasarlı":"Kayıp"}</span></td><td>{x.return_note||x.description||"—"}</td><td>{documentCell(x)}</td></tr>)}</tbody></table>{!history.length?<div className="empty"><strong>Geçmiş zimmet yok.</strong>Tamamlanan zimmetler burada kalıcı olarak görünecek.</div>:null}</section>
  </>;
}
