'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
const labels:Record<string,string>={new:'Yeni',update:'Güncellenecek',unchanged:'Değişiklik yok',error:'Kontrol gerekli',missing:'Araç bulunamadı'};
const fields:Record<string,string>={first_name:'Ad',last_name:'Soyad',phone:'Telefon',company:'Şirket',branch:'Şube',department:'Birim',requested_documents:'İstenen Belgeler',CASCO:'Kasko',INSPECTION:'Muayene',PARKING:'Otopark',TRAFFIC_INSURANCE:'Sigorta'};
export function ImportPanel({kind}:{kind:'personnel'|'compliance'}){
 const [preview,setPreview]=useState<any>(null),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const router=useRouter();
 const api=`/api/${kind==='personnel'?'personnel':'compliance'}-import`;
 async function submit(fd:FormData){setBusy(true);setError('');try{const r=await fetch(api,{method:'POST',body:fd});const data=await r.json();if(!r.ok)throw new Error(data.error||'İşlem tamamlanamadı.');if(data.result){setResult(data.result);setPreview(null);router.refresh()}else{setPreview(data);setResult(null)}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="card section"><div className="section-head"><h2 className="section-title">{kind==='personnel'?'Toplu Personel':'Araç Süre Takibi'} Excel Güncellemesi</h2></div><div className="section-body">
 <p>Boş hücreler mevcut bilgileri korur. Dosyayı seçtikten sonra değişiklikleri inceleyip uygulayın.</p>
 {kind==='personnel'?<p>Mevcut personeli güncellemek için dışa aktarılan dosyayı kullanın; gizli sistem kimliği eşleşmeyi korur. Sistem kimliği boş satırlar yeni personel olarak eklenir; aynı isimli kişiler ayrı kayıtlardır. Mevcut kayıt güncellemesinde gizli kimliği silmeyin.</p>:<p>Plaka ile yalnızca mevcut araçların süre bilgileri güncellenir. Yeni araç oluşturulmaz. Tarih biçimi: GG.AA.YYYY veya YYYY-AA-GG.</p>}
 <div className="page-actions"><a className="btn btn-secondary" href={api+(kind==='personnel'?'?export=1':'')}>Mevcut {kind==='personnel'?'Personelleri':'Araçları'} İndir</a>{kind==='personnel'?<a className="btn btn-secondary" href={api}>Örnek Excel İndir</a>:null}</div>
 <form onSubmit={e=>{e.preventDefault();setPreview(null);void submit(new FormData(e.currentTarget))}} className="form-actions"><input className="input" type="file" name="file" accept=".xlsx" required disabled={busy} onChange={()=>{setPreview(null);setResult(null)}}/><button className="btn btn-primary" disabled={busy}>{busy?'İşleniyor…':'Dosyayı Önizle'}</button></form>
 {error?<div role="alert" className="error-box">{error}</div>:null}
 {preview?<><p>Toplam Satır: {preview.plan.length} • {Object.entries(labels).map(([k,v])=>`${v}: ${preview.plan.filter((p:any)=>p.status===k).length}`).join(' • ')}</p><div className="table-wrap" style={{maxHeight:450,overflow:'auto'}}><table className="table"><thead><tr><th>Satır</th><th>Kayıt</th><th>Durum</th><th>Değişiklik / Hata</th></tr></thead><tbody>{preview.plan.map((p:any)=><tr key={p.row}><td>{p.row}</td><td>{p.label}</td><td>{labels[p.status]}</td><td>{p.message||Object.entries(p.changes).map(([k,v]:any)=>`${fields[k]||k}: ${v.old??'—'} → ${v.value}`).join(' • ')}</td></tr>)}</tbody></table></div><div className="form-actions"><button className="btn btn-primary" disabled={busy||!preview.plan.some((p:any)=>['new','update'].includes(p.status))} onClick={()=>{const fd=new FormData();fd.set('token',preview.token);void submit(fd)}}>Güncellemeyi Uygula</button><button className="btn btn-secondary" disabled={busy} onClick={()=>setPreview(null)}>Vazgeç</button></div></>:null}
 {result?<div role="status" className="success-box"><strong>İşlem sonucu</strong><p>Toplam: {result.total} • Yeni: {result.new} • Güncellenen: {result.updated} • Değişiklik olmayan: {result.unchanged} • Bulunamayan: {result.missing} • Hatalı / kontrol gereken: {result.errors.length-result.missing}</p>{result.errors.map((s:string,i:number)=><div key={i}>{s}</div>)}</div>:null}
 </div></section>;
}
