import {ImportPanel} from "@/components/import-panel";
import Link from "next/link";
import {requireUser} from "@/lib/auth";
import {getDatabase} from "@/lib/local/database";
import {ConfirmSubmitButton} from "@/components/confirm-submit-button";

export const dynamic="force-dynamic";
export default async function PersonnelPage({searchParams}:{searchParams:Promise<{q?:string;filter?:string;saved?:string;error?:string;imported?:string;failed?:string;import_errors?:string}>}){
  await requireUser();
  const sp=await searchParams,db=getDatabase();
  const q=(sp.q||"").trim(),filter="active",like=`%${q}%`;
  const where=filter==="active"?"status='ACTIVE'":filter==="passive"?"status<>'ACTIVE'":"1=1";
  const rows=db.prepare(`SELECT p.*,
    (SELECT count(*) FROM personnel_assignments pa WHERE pa.personnel_id=p.id) asset_history_count,
    (SELECT count(*) FROM vehicle_usage_records vu WHERE vu.personnel_id=p.id) vehicle_usage_count
    FROM personnel p WHERE status<>'DELETED' AND ${where} AND (?='' OR p.first_name||' '||p.last_name LIKE ? COLLATE NOCASE OR COALESCE(p.company,'') LIKE ? COLLATE NOCASE OR COALESCE(p.department,'') LIKE ? COLLATE NOCASE OR COALESCE(p.branch,'') LIKE ? COLLATE NOCASE OR COALESCE(p.phone,'') LIKE ? COLLATE NOCASE)
    ORDER BY CASE WHEN p.status='ACTIVE' THEN 0 ELSE 1 END,p.last_name,p.first_name LIMIT 300`).all(q,like,like,like,like,like) as any[];
  const departments=(db.prepare("SELECT name FROM system_definitions WHERE category='department' AND is_active=1 ORDER BY sort_order,name").all() as any[]).map(x=>x.name);
  return <><div className="page-head"><div><h1 className="page-title">Personel Yönetimi</h1><div className="page-sub">Aktif çalışanları yönetin; eski personelin geçmiş kayıtlarını silmeden günlük listelerden kaldırın.</div></div></div>
  {sp.saved?<div className="success-box">{sp.saved==='removed'?'Personel silindi. Geçmiş kayıtları korunuyor.':'İşlem başarıyla kaydedildi.'}</div>:null}{sp.imported!=null?<div className="success-box">{Number(sp.imported||0)} personel başarıyla eklendi{Number(sp.failed||0)>0?`, ${Number(sp.failed)} kayıt hatalı olduğu için eklenmedi.`:"."}</div>:null}{sp.import_errors?<div className="warning-box">{decodeURIComponent(sp.import_errors)}</div>:null}{sp.error?<div className="error-box">{sp.error}</div>:null}
  <ImportPanel kind="personnel"/><div className="two-col section"><form action="/api/personnel" method="post" className="card"><input type="hidden" name="operation" value="create"/><input type="hidden" name="return_to" value="/personel-yonetimi"/><div className="section-head"><div><div className="section-title">Yeni Personel</div><div className="page-sub">Aktif olarak eklenen personel zimmet ve günlük araç teslim ekranlarında hemen seçilebilir.</div></div></div><div className="section-body"><div className="form-grid"><div className="field"><label>Ad *</label><input className="input" name="first_name" required/></div><div className="field"><label>Soyad *</label><input className="input" name="last_name" required/></div><div className="field"><label>Şirket *</label><input className="input" name="company"  required/></div><div className="field"><label>Şube *</label><input className="input" name="branch"  required/></div><div className="field"><label>Birim *</label><input className="input" name="department"  required/></div><div className="field"><label>İstenen Belgeler</label><input className="input" name="requested_documents"  /></div><div className="field"><label>Telefon</label><input className="input" name="phone" inputMode="tel" placeholder="05xx xxx xx xx"/></div></div><div className="form-actions"><button className="btn btn-primary">Personel Ekle</button></div></div></form>
  <section className="card"><div className="section-head"><div className="section-title">Kural</div></div><div className="section-body"><div className="notice"><strong>Personel silindiğinde geçmiş işlemleri korunur.</strong> Yalnızca yeni işlemlerde ve aktif seçim listelerinde görünmez. Silinen kişi personel listelerinde ve yeni işlemlerde görünmez.</div></div></section></div>
  <form className="filters section" method="get"><input className="input filter-search" name="q" defaultValue={q} placeholder="Ad soyad, şirket, şube, birim veya telefon ara…"/><button className="btn btn-primary">Filtrele</button>{q||filter!=="active"?<Link className="btn btn-secondary" href="/personel-yonetimi">Temizle</Link>:null}</form>
  <section className="card section table-wrap"><div className="section-head"><div><div className="section-title">Personeller</div><div className="page-sub">Varsayılan görünüm yalnızca aktif personellerdir.</div></div></div><table className="table"><thead><tr><th>Ad Soyad</th><th>Şirket</th><th>Şube</th><th>Birim</th><th>Telefon</th><th>Durum</th><th>Geçmiş</th><th>İşlem</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><Link className="link-primary" href={`/personel-yonetimi/${p.id}`}>{p.first_name} {p.last_name}</Link></td><td>{p.company||"—"}</td><td>{p.branch||"—"}</td><td>{p.department||"—"}</td><td>{p.phone||"—"}</td><td><span className={`pill ${p.status==='ACTIVE'?'green':'gray'}`}>{p.status==='ACTIVE'?'Aktif':'Eski / Pasif'}</span></td><td>{Number(p.asset_history_count)} zimmet • {Number(p.vehicle_usage_count)} araç kullanımı</td><td>{<form action="/api/personnel" method="post"><input type="hidden" name="operation" value="deactivate"/><input type="hidden" name="personnel_id" value={p.id}/><input type="hidden" name="return_to" value={`/personel-yonetimi?filter=${filter}`}/><ConfirmSubmitButton message={`${p.first_name} ${p.last_name} isimli personeli kaldırmak istediğinize emin misiniz? Personel yeni işlemlerde görünmeyecek ancak geçmiş kayıtları korunacaktır.`}>Personeli Sil</ConfirmSubmitButton></form>}</td></tr>)}</tbody></table>{!rows.length?<div className="empty"><strong>Personel bulunamadı.</strong>Seçili filtreye uygun kayıt yok.</div>:null}</section></>;
}
