import Link from "next/link";
import {notFound} from "next/navigation";
import {requireUser} from "@/lib/auth";
import {getDatabase} from "@/lib/local/database";
import {formatDateTime,formatNumber} from "@/lib/format";
import {ConfirmSubmitButton} from "@/components/confirm-submit-button";
import {SubmitButton} from "@/components/submit-button";

export const dynamic="force-dynamic";
export const revalidate=0;

export default async function VehicleQrDetail({params,searchParams}:{params:Promise<{vehicleId:string}>;searchParams:Promise<{saved?:string;error?:string}>}){
  await requireUser(); const {vehicleId}=await params; const sp=await searchParams; const db=getDatabase();
  const row=db.prepare(`SELECT v.id,v.plate,v.brand,v.model,v.current_odometer,v.is_active vehicle_active,q.id qr_id,q.is_active qr_active,q.created_at,q.rotated_at,q.disabled_at,q.last_used_at
    FROM vehicles v LEFT JOIN vehicle_qr_codes q ON q.vehicle_id=v.id WHERE v.id=? AND v.is_replacement=0`).get(vehicleId) as any;
  if(!row)notFound();
  const history=row.qr_id?db.prepare("SELECT * FROM vehicle_qr_km_updates WHERE vehicle_id=? ORDER BY datetime(created_at) DESC LIMIT 250").all(vehicleId) as any[]:[];
  return <div className="page-stack">
    <div className="page-header"><div><div className="breadcrumb"><Link href="/arac-qr-km-guncelleme">Araç QR / KM Güncelleme</Link><span>›</span><span>{row.plate}</span></div><h1>{row.plate} QR Kodu</h1><div className="page-sub">QR okutulduğunda yalnızca bu aracın Güncel KM bildirim ekranı açılır.</div></div><div className="header-actions"><Link className="btn btn-secondary" href={`/arac-qr-km-guncelleme/yazdir?vehicle_id=${vehicleId}`}>Yazdır</Link>{row.qr_id?<a className="btn btn-secondary" href={`/api/vehicle-qr/image?vehicle_id=${vehicleId}&download=1`}>QR İndir</a>:null}</div></div>
    {sp.saved?<div className="success-box">İşlem başarıyla kaydedildi.</div>:null}{sp.error?<div className="error-box">{String(sp.error)}</div>:null}
    <div className="two-col qr-detail-grid"><section className="card section"><div className="section-head"><div><div className="section-title">QR Etiketi</div><div className="page-sub">{[row.brand,row.model].filter(Boolean).join(" ")}</div></div>{row.qr_id?(Number(row.qr_active)===1&&Number(row.vehicle_active)===1?<span className="pill green">Aktif</span>:<span className="pill red">Pasif</span>):<span className="pill gray">Oluşturulmadı</span>}</div><div className="qr-label-preview">{row.qr_id?<><div className="qr-label-brand">İDARİ İŞLER PORTALI</div><img src={`/api/vehicle-qr/image?vehicle_id=${vehicleId}`} alt={`${row.plate} KM QR Kodu`} className="qr-image"/><strong>{row.plate}</strong><span>Güncel KM Bildirmek İçin Okutun</span></>:<div className="empty">Bu araç için henüz QR kodu oluşturulmadı.</div>}</div></section>
      <section className="card section"><div className="section-title">Araç ve QR Bilgileri</div><div className="detail-list"><div><span>Güncel KM</span><strong>{formatNumber(Number(row.current_odometer||0))} KM</strong></div><div><span>QR Oluşturma</span><strong>{formatDateTime(row.created_at)}</strong></div><div><span>Son QR Güncellemesi</span><strong>{formatDateTime(row.last_used_at)}</strong></div><div><span>Son QR Yenileme</span><strong>{formatDateTime(row.rotated_at)}</strong></div></div><div className="section qr-actions">{!row.qr_id&&Number(row.vehicle_active)?<form action="/api/vehicle-qr" method="post"><input type="hidden" name="operation" value="create"/><input type="hidden" name="vehicle_id" value={vehicleId}/><input type="hidden" name="return_to" value={`/arac-qr-km-guncelleme/${vehicleId}`}/><SubmitButton>QR Oluştur</SubmitButton></form>:null}{row.qr_id?<><form action="/api/vehicle-qr" method="post"><input type="hidden" name="operation" value="rotate"/><input type="hidden" name="vehicle_id" value={vehicleId}/><input type="hidden" name="return_to" value={`/arac-qr-km-guncelleme/${vehicleId}`}/><ConfirmSubmitButton className="btn btn-secondary" message="QR kodu yenilenecek. Daha önce basılmış eski QR artık çalışmayacak. Devam edilsin mi?">QR Kodunu Yenile</ConfirmSubmitButton></form>{Number(row.qr_active)===1?<form action="/api/vehicle-qr" method="post"><input type="hidden" name="operation" value="disable"/><input type="hidden" name="vehicle_id" value={vehicleId}/><input type="hidden" name="return_to" value={`/arac-qr-km-guncelleme/${vehicleId}`}/><ConfirmSubmitButton message="Bu QR devre dışı bırakılırsa saha üzerinden KM güncellenemez. Devam edilsin mi?">Devre Dışı Bırak</ConfirmSubmitButton></form>:Number(row.vehicle_active)?<form action="/api/vehicle-qr" method="post"><input type="hidden" name="operation" value="enable"/><input type="hidden" name="vehicle_id" value={vehicleId}/><input type="hidden" name="return_to" value={`/arac-qr-km-guncelleme/${vehicleId}`}/><SubmitButton>QR'ı Etkinleştir</SubmitButton></form>:null}</>:null}</div></section></div>
    <section className="card table-wrap" id="history"><div className="section-head"><div><div className="section-title">QR KM Güncelleme Geçmişi</div><div className="page-sub">QR üzerinden yapılan bütün kilometre girişleri kalıcı olarak tutulur.</div></div></div><table className="table"><thead><tr><th>Tarih / Saat</th><th>Önceki KM</th><th>Yeni KM</th><th>Fark</th><th>Kaynak</th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td>{formatDateTime(x.created_at)}</td><td>{formatNumber(Number(x.previous_odometer))} KM</td><td><strong>{formatNumber(Number(x.new_odometer))} KM</strong></td><td>+{formatNumber(Number(x.difference))} KM</td><td><span className="pill blue">QR Kod</span></td></tr>)}</tbody></table>{!history.length?<div className="empty">Henüz QR üzerinden KM güncellemesi yapılmadı.</div>:null}</section>
  </div>
}
